### ISSUE TITLE
Update projects to latest .NET SDK

### ISSUE THREAD

**Issue by ErikSchierboom** [PomeloFoundation/Lolita#11]
The projects currently use the deprecated `.xproj` format. It is probably a good idea to upgrade the projects to the new `.csproj` format, similar to what is done in the [Pomelo.EntityFrameworkCore.MySql project](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/EFCore.MySql.csproj).

**Comment by yukozh** [comment]
You can try it in https://www.myget.org/F/pomelo/api/v3/index.json
Pomelo.EntityFrameworkCore.Lolita.MySql 2.0.0-preview2-final

**Comment by ErikSchierboom** [comment]
@Kagamine Can I find the source for that release somewhere? I don't see a 2.0.0 branch.

**Comment by yukozh** [comment]
in master branch

**Comment by ErikSchierboom** [comment]
@Kagamine Ah yes, missed it somehow.
