### ISSUE TITLE
SqlServer Compact provider

### ISSUE THREAD

**Issue by ErikEJ** [PomeloFoundation/Lolita#2]
Add support for the sql server compact provider

**Comment by yukozh** [comment]
Hi @ErikEJ , I will implement this tomorrow, Thanks for your suggestion

**Comment by ErikEJ** [comment]
Great, thanks! Looking forward t trying it out!

**Comment by yukozh** [comment]
Hi @ErikEJ ,Can you have a try to use Lolita.SqlServer in Sql Server Compact? Lolita just packing the update operations which ef did not supported(https://github.com/PomeloFoundation/Lolita/blob/master/src/Pomelo.EntityFrameworkCore.Lolita.SqlServer/Update/SqlServerSetFieldSqlGenerator.cs). In other words, if you want to support another database, just implement a SetFieldSqlGenerator will make the new database work. I have refered to the document, it seems that the operations in which Sql Server Compact is similar to Sql Server. 

https://technet.microsoft.com/en-us/library/ms174470(v=sql.110).aspx

**Comment by yukozh** [comment]
@ErikEJ  Could you have a look at the operations which listed in the README.md, We should confirm the SQL between SQL Server and SQL Server Compact are same or not.

**Comment by ErikEJ** [comment]
Yes, I have put it in my backlog to do this sometime.

**Comment by yukozh** [comment]
:smile:
