### ISSUE TITLE
Isn't it vulnerable for SQL Injection?

### ISSUE THREAD

**Issue by TsengSR** [PomeloFoundation/Lolita#4]
Stumbled upon it from another GitHub repository and found [this](https://github.com/PomeloFoundation/Lolita/blob/master/src/Pomelo.EntityFrameworkCore.Lolita.SqlServer/Update/SqlServerSetFieldSqlGenerator.cs#L13-L44) (Generators for other databases affected too):

```
                case "WithValue":
                    return $"{operation.Field} = {{{ operation.Index }}}";
                case "Plus":
                    return $"{operation.Field} = {operation.Field} + {{{ operation.Index }}}";
                case "Subtract":
                    return $"{operation.Field} = {operation.Field} - {{{ operation.Index }}}";
```

etc. Isn't that vulnerable to SQL Injections? The official SqlServer generators use `SqlServerSqlGenerationHelper.GenerateLiteralValue(operation.Value)` ([here](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerSqlGenerationHelper.cs#L112)) and `SqlServerSqlGenerationHelper.DelimitIdentifier(operation.Field)` ([here](https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore.SqlServer/Storage/Internal/SqlServerSqlGenerationHelper.cs#L76)) to escape the values (literally replacing placing a single-quote in front (or N' for unicode) and replacing all single-quotes with two single-quotes)

**Comment by yukozh** [comment]
Dont think there was sql injection bug. We have used SqlGenerator and parameters when execute the sql. Not familiar to sqlserver.
